### PR TITLE
Fix space after macro call start, use indent string as found in code

### PR DESCRIPTION
**Pull request by mlange-42**
Minor fix of spaces and indentation in reverse mode

### CODE REVIEW

**Comment by adamreichold** [comment]
Clippy is not happy. This also contains commits from #60, so the target branch should probably change.

**Comment by mlange-42** [comment]
Fixed clippy, changed target branch

**Comment by adamreichold** [comment]
Needs a rebase...

**Comment by mlange-42** [comment]
I can give it a try, but not sure if I will manage that.

**Comment by adamreichold** [comment]
> I can give it a try, but not sure if I will manage that.

In this case, you'll have to as this contains an outdated commit that you force-pushed in #60. Just do `rebase -i origin/dev` and drop the first commit because it is not needed anymore.

**Review by adamreichold — APPROVED** [review]

**Pull request merged**
