### PR TITLE
Rework of examples

### LINKED ISSUE #68: [Examples] Add examples for other languages than Rust (Java, NetLogo)

### LINKED ISSUE #69: [Examples] Ignore output folders of examples?

### PR DESCRIPTION
**Pull request by mlange-42**
* [x] Ignore output of example
* [x] Simplify installation instructions
* [x] Add an example for Java and Gradle
* [x] Add a NetLogo example
* [x] Add a Python example

Fixes #68
Fixes #69

### CODE REVIEW

**Comment by adamreichold** [comment]
I would be glad if we could merge the default_setup and features_demo examples into a single rust example.

**Comment by mlange-42** [comment]
As `default_setup` is just what is created with `init`, I would simply delete it. What do you thinkabout activating the reverse mode in the then `rust` example, and describe it like in the netlogo example (except for the netlogo complications)?

**Comment by mlange-42** [comment]
Done. Moved remarks on dreverse mode in the netlogo example to the borrom

**Comment by adamreichold** [comment]
> What do you thinkabout activating the reverse mode in the then rust example

Yes, I think reverse mode makes most sense for languages like Rust and Java which provide good native tooling like formatters and IDE which one would want to use, but which cannot handle the literate program.

**Comment by adamreichold** [comment]
(A proper review on my part will not happen before tomorrow, but don't let yourself be held up if you are in a hurry.)

**Comment by mlange-42** [comment]
Ok, thanks for letting me know. I will see. I case I venture to give the restructuring that you suggested a try, I would prefer to utilize your capacity for that.

**Pull request merged**
