### PR TITLE
[Withdrawn] Task-oriented module structure

### PR DESCRIPTION
**Pull request by mlange-42**
*[Withdrawn] Still here for comparison with step-wise re-structuring.*

A trial to restructure according #57.

So far:

* Moved parser and document functions to modules `parse` and `print`
* Moved compile-related functions from `main` to modules `compile` and `compile_reverse`
* Removed struct `CodeParser`, moved functionality to module `code`

@adamreichold Any advice, or an independent trial, is highly appreciated.

### CODE REVIEW

**Comment by adamreichold** [comment]
> Any advice, or an independent trial, is highly appreciated.

Instead of a duplicate approach, I would prefer making this easier to review by breaking it up. For example, create on new module per pull request. Or even smaller steps. (Of course, I can look at individual commits here, but the discussion should be scoped as well. And since you already have individual commits, it should also be straight forward to break this into independent pull requests.)

**Comment by mlange-42** [comment]
I tried to break it into commits, but it was not possible to do it module by module. I can, however, start with a MR for the first commit.

**Comment by mlange-42** [comment]
My impression was that this is basically only moving around code, so the overall structure changes but content not. So I thought you would primarily focus on the overall structure rather than diffs, anyway. But maybe more places for improvement become obvious by doing it step by step.

**Comment by adamreichold** [comment]
> But maybe more places for improvement become obvious by doing it step by step.

Often, doing larger reshuffling of a code base is also used to tease out other improvements since you are reading through all of it anyway.

**Comment by mlange-42** [comment]
Done in #89, #98, #99, #102, #103, #104.

**Pull request closed without merging**
