### PR TITLE
Replace bespoke lazy join by dependency on display_utils crate.

### PR DESCRIPTION
**Pull request by adamreichold**
On a cursory look, I did not find another place we I'd jump for `display_utils` though...

### CODE REVIEW

**Comment by adamreichold** [comment]
@mlange-42 Do we want to pull in the dependency?

**Comment by mlange-42** [comment]
Sorry for the delay, this got lost somehow. As we still use the new dependency only for the joins, but no other of its functionality, I am a bit undecided.

**Comment by adamreichold** [comment]
If we do not use them, the changes to `print.rs` should probably be applied using our own lazy join.

**Comment by adamreichold** [comment]
#180 would be that alternative if we do not want a dependency on `display_utils`.

**Pull request closed without merging**
